server:
  port: 8080
spring:
  application:
    name: "auth-crediya"
  devtools:
    add-properties: false
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

# PostgreSQL Configuration
adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: autenticacion_db
    schema: public
    username: postgres
    password: password123
