# Test Configuration
spring:
  profiles:
    active: test
  datasource:
    url: jdbc:tc:postgresql:15:///testdb
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: test
    password: test
  r2dbc:
    url: r2dbc:tc:postgresql:///testdb?TC_IMAGE_TAG=15
    username: test
    password: test

logging:
  level:
    root: INFO
    co.com.bancolombia: DEBUG